apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    app: {{ template "eha-care.name" . }}
    chart: {{ template "eha-care.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    io.kompose.service: eha-care
  name: {{ template "eha-care.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "eha-care.name" . }}
    release: {{ .Release.Name }}
    io.kompose.service: eha-care
status:
  loadBalancer: {}
